### ISSUE TITLE
Please add support for Bitbucket Teams

### ISSUE THREAD

**Issue by npadgen** [hirakiuc/tinybucket#128]
Please add support for Bitbucket Teams (https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams).

Our Bitbucket instance has lots of repos which we organise by Team.  I would like to iterate through each project's repos for reports, e.g. number of open pull requests per team.

To do this I'd like to be able to:
- list the teams;
- find the repos belonging to each team.

**Comment by hirakiuc** [comment]
> Please add support for Bitbucket Teams 

Oh, I think that I forgot to implement part of teams API. 🙇 

I try to implement the rest of teams API in next weekend. 💪

**Comment by hirakiuc** [comment]
Ref: #130

**Comment by hirakiuc** [comment]
I released version 1.5.0 😃 

This version includes the features what you want.

```ruby
bucket = Tinybucket.new

bucket.teams(role).each do |team|
  team.repos.each do |repo|
    # Do something with Tinybucket::Model::Repository
    puts repo.name
  end
end
```

And also you can iterate repositories by projects, like this. ✨ 

```ruby
bucket = Tinybucket.new

bucket.teams(role).each do |team|
  team.projects.each do |project|
    project.repos.each do |repo|
      # Do something with Tinybucket::Model::Repository
      puts repo.name
    end
  end
end
```

Please enjoy version 1.5.0. 👍

**Comment by npadgen** [comment]
Looks very good, but now I'm getting a problem iterating through repos.

```ruby
  b.teams('admin').each do |team|
    team.projects.each do |project|
      next unless project.name == 'DevOps'
      project.repos.each do |repo|
        puts repo
      end
    end
  end
```

gives:

```
#<Tinybucket::Model::Repository:0x007fe051a9eb68>
#<Tinybucket::Model::Repository:0x007fe051a97bd8>
#<Tinybucket::Model::Repository:0x007fe051a8f208>
#<Tinybucket::Model::Repository:0x007fe051a8dc78>
#<Tinybucket::Model::Repository:0x007fe051a8c328>
#<Tinybucket::Model::Repository:0x007fe05320e848>
#<Tinybucket::Model::Repository:0x007fe053207408>
#<Tinybucket::Model::Repository:0x007fe0532044d8>
#<Tinybucket::Model::Repository:0x007fe0531fd1b0>
#<Tinybucket::Model::Repository:0x007fe05316a540>
ArgumentError: odd number of arguments for Hash
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/iterator.rb:72:in `[]'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/iterator.rb:72:in `next_params'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/iterator.rb:60:in `load_next'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/iterator.rb:46:in `next_value'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/iterator.rb:25:in `next'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/enumerator.rb:19:in `block (2 levels) in initialize'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/enumerator.rb:18:in `loop'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/enumerator.rb:18:in `block in initialize'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/resource/base.rb:14:in `each'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/resource/base.rb:14:in `each'
	from /Users/neilp/lib/gems/gems/tinybucket-1.5.0/lib/tinybucket/resource/base.rb:14:in `method_missing'
	from (irb):301
	from /usr/local/bin/irb:11:in `<main>'
```

There should be 71 repos listed for this project.

**Comment by hirakiuc** [comment]
Oh, Sorry about that. 🙇 

I'll investigate.

**Comment by npadgen** [comment]
Seems to happen for every project with more than 10 repos.  It throws the ArgumentError after the tenth repo.

**Comment by hirakiuc** [comment]
Thank you for your report 😃 

Yes, it looks like a bug on iterating any resource with the specific query params.
I'll fix that soon. 👍

**Comment by hirakiuc** [comment]
Please try with v1.5.1 which includes the bug fix about your problem. 😃

**Comment by npadgen** [comment]
It works perfectly!  Thank you so much for this.
