### ISSUE TITLE
undefined method `uuid=` for #<Tinybucket::Model::Repository:... (NoMethodError)

### ISSUE THREAD

**Issue by hirakiuc** [hirakiuc/tinybucket#42]
NoMethodError raised when call load method to repository.

```
E, [2014-09-17T10:29:13.274348 #95690] ERROR -- : undefined method `uuid=' for #<Tinybucket::Model::Repository:0x007fe52141e9a8> (NoMethodError)
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/model/base.rb:19:in `block in attributes='
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/model/base.rb:19:in `each'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/model/base.rb:19:in `attributes='
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/model/base.rb:13:in `initialize'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/parser/repo_parser.rb:6:in `new'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/parser/repo_parser.rb:6:in `convert'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/parser/base_parser.rb:5:in `process_response'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/request.rb:31:in `request'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/request.rb:4:in `get_path'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/api/repo_api.rb:9:in `find'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/model/repository.rb:92:in `load_model'
/Users/hirakiuc/Desktop/tool/bitbucket/.bundle/ruby/2.1.0/gems/tinybucket-0.1.1/lib/tinybucket/model/concerns/reloadable.rb:13:in `load'
app.rb:18:in `block in <main>'
```

**Comment by hirakiuc** [comment]
fixed by pull request #43
