### ISSUE TITLE
NoMethodError: undefined method `merge!' for "branch_name":String

### ISSUE THREAD

**Issue by atchyut-re** [hirakiuc/tinybucket#96]
When I was trying to retrieve commit messages from a particular branch by looping all the commits of the branch as mentioned in the documentation.

Documentation:
```
repo = bucket.repo('someone', 'great_repo')

# [x] GET a commits list for a repository or compare commits across branches
# branchortag, include, exclude options
commits = repo.commits(options)
```

My code:
```
commits = repo.commits('branch_name')
 #<Tinybucket::Resource::Commits:0x00000005faca30 @repo=#<Tinybucket::Model::Repository:0x00000007afef68 @_loaded=false, @repo_owner="owner_name", @repo_slug="sample_app">, @args=["static-pages-exercises"]> 

commits.each do |commit|
    puts commit.message
end
```

Error message after that loop:
```
NoMethodError: undefined method `merge!' for "branch_name":String
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/iterator.rb:73:in `next_params'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/iterator.rb:58:in `load_next'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/iterator.rb:44:in `next_value'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/iterator.rb:23:in `next'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/enumerator.rb:17:in `block (2 levels) in initialize'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/enumerator.rb:16:in `loop'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/enumerator.rb:16:in `block in initialize'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/resource/base.rb:12:in `each'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/resource/base.rb:12:in `each'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/tinybucket-1.2.0/lib/tinybucket/resource/base.rb:12:in `method_missing'
	from (irb):357
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/atchyut/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'2.3.0 :360 > 
```

Can someone please explain how should I have to send branch name for the options argument to retrieve individual commit messages?

**Comment by hirakiuc** [comment]
Hi, again ! 😄 

Sorry about poor documentation. 😭 

I didn't explain in any documentation about How to pass query parameters to each method.

Here is example code. 😋 

## How to get commits in a branch.

This code shows you the commits which are included in `use_foreman` branch, not included in  `master` branch in `hirakiuc/site_meta` private repository. 

```
Tinybucket.configure do |config|
  config.oauth_token = 'my oauth1.0 key'
  config.oauth_secret = 'my oauth1.0 secret'
end

bucket = Tinybucket.new

repo = bucket.repo('hirakiuc', 'site_meta')
repo.commits(include: 'use_foreman', exclude: 'master').each do |commit|
   puts "#{commit.hash}: #{commit.message}"
end
```

This code passes the `{include: 'use_foreman', exclude: 'master}` hash as options argument to commits method.

Yes! As you see, the key/value pair in this `options` hash is used to query parameter !

Please check [the documentation](
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/commits) about what kind of query parameters you can use.

If you want to get all of commits in `use_foreman` branch, you just only pass `{include: 'use_foreman'}` hash to commits method. 👍

**Comment by atchyut-re** [comment]
@hirakiuc Thanks for a really quick reply. It works like charm.
No problem, we all can work together to update the documentation more helpful.
